[package]
name = "fake"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"

#[[test]]
#name = "my_tests"
#path = "tests/foo_tests.rs"
